// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Aplicacion.Dominio.Entidades;
using Aplicacion.Persistencia.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace Aplicacion.Persistencia
{
    public partial class CursoContext : DbContext
    {
        public CursoContext()
        {
        }

        public CursoContext(DbContextOptions<CursoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Estudiantes> Estudiantes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.EstudiantesConfiguration());
            
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
