// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Aplicacion.Dominio.Entidades;
using Aplicacion.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Aplicacion.Persistencia.Configurations
{
    public partial class EstudiantesConfiguration : IEntityTypeConfiguration<Estudiantes>
    {
        public void Configure(EntityTypeBuilder<Estudiantes> entity)
        {
            entity.Property(e => e.Apellidos)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Direccion)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FechaNacimiento).HasColumnType("date");

            entity.Property(e => e.Nombres)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Estudiantes> entity);
    }
}
